# Generated by Django 5.0.1 on 2024-01-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=32, unique=True)),
                ('company_name', models.CharField(max_length=128, null=True)),
                ('industry', models.CharField(max_length=512)),
                ('sector', models.CharField(max_length=128, null=True)),
            ],
        ),
    ]
